[package]
name = "ast"
version = "0.1.0"
edition = "2024"

[dependencies]
tokenizer = { path = "../tokenizer" }
diagnostic = { path = "../diagnostic" }
serde.workspace = true

[dev-dependencies]
indoc.workspace = true
