[package]
name = "parser"
version = "0.1.0"
edition = "2024"

[dependencies]
tokenizer = { path = "../tokenizer" }
syntax_tree = { path = "../syntax_tree" }

[dev-dependencies]
indoc.workspace = true
